version: '3'
services:
  consumer:
    image: kafka-consumer:1.0.0
    networks: 
      - broker-kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka
      BOOTSTRAP_PORT: '29092'

  producer:
    image: kafka-producer:1.0.0
    networks: 
      - broker-kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka
      BOOTSTRAP_PORT: '29092'

networks: 
  broker-kafka:
    driver: bridge  